version: "3.9"

services:

  order_db:
    container_name: "order_db"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_PASSWORD=root
    volumes:
      - order_db-data:/var/lib/postgresql/data

volumes:
  order_db-data:
    driver: local
