spring:
  application:
    name: OrderService

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true


