spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgres

springdoc:
  packagesToScan: com.givendtake.orderMicroservice
